In [1]:
import numpy as np

Create the array

In [2]:
x = np.array([56,12,34,54,6,33,54])

In [3]:
print(x)

[56 12 34 54  6 33 54]


In [4]:
type(x)

numpy.ndarray

In [7]:
x.ndim #gives dimension

1

In [8]:
x

array([56, 12, 34, 54,  6, 33, 54])

In [9]:
x.dtype

dtype('int32')

In [12]:
x = np.array([56,12,34,54,6,33,54], dtype = np.int8)

In [13]:
x

array([56, 12, 34, 54,  6, 33, 54], dtype=int8)

In [15]:
x = np.array([56,12,34,54,6,33,128], dtype = np.int8)

C:\Users\rajesh\AppData\Local\Temp\ipykernel_3304\483426161.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  x = np.array([56,12,34,54,6,33,128], dtype = np.int8)


In [21]:
x = np.array([56,12,34,54,6,33,128], dtype = np.int64)

In [19]:
x.dtype

dtype('int64')

In [22]:
x.size

7

In [23]:
x.shape

(7,)

In [25]:
x.min()

6

In [27]:
x.sort
x

array([  6,  12,  33,  34,  54,  56, 128], dtype=int64)

In [28]:
x.std()

37.71482683594486

In [29]:
x.nonzero()

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [36]:
y = np.array([1,2,3,4.5,66,77])

In [38]:
y.dtype

dtype('float64')

In [39]:
y

array([ 1. ,  2. ,  3. ,  4.5, 66. , 77. ])

In [40]:
z = np.array([1,2,3,4.5,66,True])

In [41]:
z.dtype

dtype('float64')

In [42]:
z

array([ 1. ,  2. ,  3. ,  4.5, 66. ,  1. ])

In [43]:
z = np.array([1,2,3,4.5,66,'True'])

In [44]:
z

array(['1', '2', '3', '4.5', '66', 'True'], dtype='<U32')

In [47]:
z.dtype

dtype('<U32')

In [48]:
p = 'charan'

In [49]:
p.dtype

AttributeError: 'str' object has no attribute 'dtype'

q = np.zeroes(10, dtype=np.int16)
q

In [52]:
q = np.ones(10, dtype=np.int16)
q

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [54]:
q = np.zeros(10, dtype=np.int16)
q

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [55]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [57]:
np.arange(5,10,0.33)

array([5.  , 5.33, 5.66, 5.99, 6.32, 6.65, 6.98, 7.31, 7.64, 7.97, 8.3 ,
       8.63, 8.96, 9.29, 9.62, 9.95])

In [59]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

Array Operations

In [61]:
num1 = np.array([34,5,24,5,8,33])
num2 = np.array([45,56,24,5,77,2])

In [62]:
num1 + 10

array([44, 15, 34, 15, 18, 43])

In [63]:
num2 / 5

array([ 9. , 11.2,  4.8,  1. , 15.4,  0.4])

In [64]:
[45,53,24,23,32] * 3

[45, 53, 24, 23, 32, 45, 53, 24, 23, 32, 45, 53, 24, 23, 32]

In [65]:
num1 + num2

array([79, 61, 48, 10, 85, 35])

Matrix

In [82]:
M = np.array([[4,5,6],[3,4,5],[1,2,3],[7,8,9]])
M

array([[4, 5, 6],
       [3, 4, 5],
       [1, 2, 3],
       [7, 8, 9]])

In [68]:
M.dtype

dtype('int32')

In [69]:
M.ndim

2

In [71]:
M[2,2]

3

In [83]:
M[0:2,1:3] #slicing

array([[5, 6],
       [4, 5]])

In [84]:
M.reshape(3,4)

array([[4, 5, 6, 3],
       [4, 5, 1, 2],
       [3, 7, 8, 9]])

In [85]:
M[0:2,1:3] = np.array([[7,8],[9,10]])

In [86]:
M

array([[ 4,  7,  8],
       [ 3,  9, 10],
       [ 1,  2,  3],
       [ 7,  8,  9]])

In [88]:
M.reshape(2,-1) #adjusts columns accordingly

array([[ 4,  7,  8,  3,  9, 10],
       [ 1,  2,  3,  7,  8,  9]])

In [90]:
M.reshape(-1) #makes into one dimension

array([ 4,  7,  8,  3,  9, 10,  1,  2,  3,  7,  8,  9])

In [91]:
M.flatten()

array([ 4,  7,  8,  3,  9, 10,  1,  2,  3,  7,  8,  9])

In [92]:
M.T

array([[ 4,  3,  1,  7],
       [ 7,  9,  2,  8],
       [ 8, 10,  3,  9]])

In [93]:
help(M.min)

Help on built-in function min:

min(...) method of numpy.ndarray instance
    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function



In [94]:
M.min()

1

In [95]:
M.min(axis=0) #row by row

array([1, 2, 3])

In [96]:
M.min(axis=1) #col by col

array([4, 3, 1, 7])

In [97]:
M.sum(axis=0)

array([15, 26, 30])

In [98]:
y.reshape(3,2)

array([[ 1. ,  2. ],
       [ 3. ,  4.5],
       [66. , 77. ]])

In [100]:
M.astype(np.float16)

array([[ 4.,  7.,  8.],
       [ 3.,  9., 10.],
       [ 1.,  2.,  3.],
       [ 7.,  8.,  9.]], dtype=float16)

In [101]:
x

array([  6,  12,  33,  34,  54,  56, 128], dtype=int64)

In [102]:
y = x

In [103]:
y

array([  6,  12,  33,  34,  54,  56, 128], dtype=int64)

In [104]:
y[0]=20

In [105]:
y

array([ 20,  12,  33,  34,  54,  56, 128], dtype=int64)

In [106]:
x

array([ 20,  12,  33,  34,  54,  56, 128], dtype=int64)

In [107]:
id(y)

2757713652752

In [109]:
id(x) #x and y are sharing same memory location 

2757713652752

In [110]:
x[0] = 1;
x

array([  1,  12,  33,  34,  54,  56, 128], dtype=int64)

In [111]:
y = x.copy()
y

array([  1,  12,  33,  34,  54,  56, 128], dtype=int64)

In [112]:
y[0]=21

In [113]:
y

array([ 21,  12,  33,  34,  54,  56, 128], dtype=int64)

In [114]:
x

array([  1,  12,  33,  34,  54,  56, 128], dtype=int64)

In [117]:
id(x);
id(y);