In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
pip install tensorflow -U

Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 2.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/377.0 MB 5.2 MB/s eta 0:01:13
   ---------------------------------------- 0.5/377.0 MB 8.3 MB/s eta 0:00:46
   ---------------------------------------- 1.0/377.0 MB 8.6 MB/s eta 0:00:44
   ---------------------------------------- 2.4/377.0 MB 17.0 MB/s eta 0:00:23
    --------------------------------------- 4.8/377.0 MB 25.3 MB/s eta 0:00:15
    --------------------------------------- 7.9/377.0 MB 36.1 MB/s eta 0:00:11
   - -------------------------------------- 11.3/377.0 MB 73.1 MB/s eta 0:00:06
   - -------------------------------------- 14

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [4]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [1]:
import tensorflow as tf

In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [3]:
#create tensors
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

In [4]:
print('tensor a:',a)
print('tensor b:',b)

tensor a: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tensor b: tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [5]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
x = tf.constant([[1,2,3],[7,8,9]])
y = tf.constant([[4,5,6],[1,2,3]])

In [8]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]])>

In [12]:
x = tf.constant([[[1,2,3],[7,8,9]],[[3,4,5],[5,6,7]]])

In [13]:
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [7, 8, 9]],

       [[3, 4, 5],
        [5, 6, 7]]])>

In [14]:
#Add tensors
c = a+b

In [15]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [16]:
c.numpy()

array([5, 7, 9])

In [17]:
a//b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [21]:
b//a #floor division

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 2])>

In [20]:
b/a #float division

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2.5, 2. ])>

In [32]:
import numpy as np

In [34]:
#Matrix multiplication
a_mx = tf.constant([[2,3],[4,5]],dtype=np.int32)
b_mx = tf.constant([[2,3],[4,5]].dtype=np.int8)
c = tf.matmul(a_mx,b_mx)
print(c)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (4110556274.py, line 3)